### ISSUE TITLE
Does this support other signal servers/websockets?

### ISSUE THREAD

**Issue by peterclemenko** [bengreenier/webrtc-unity-plugin#10]
Does this support other signal servers/websockets? It would be useful to have the ability to use a more featured signal server with less manual work involved in getting it running. Auto join/leave support, etc.

**Comment by mdanilowski** [comment]
Seems like there is no such support, but I agree that it would be very useful. @bengreenier Is it planned? If not then could you at least give us a few tips on the implementation? I need a solution that will be good for production and surely this one with the dss isn't.

**Comment by bengreenier** [comment]
Not anytime soon, sorry. I don't have much time to work on this lately as I've had to transition to a different project for work. You can take a look at [this file](https://github.com/bengreenier/webrtc-unity-plugin/blob/master/Assets/UnityWebrtc/WebrtcSignalControls.cs#L181), and replace 

```
private IEnumerator PostToServer(ServerMessage msg)
```
and 
```
private IEnumerator CO_GetAndProcessFromServer()
```

with custom logic to send data to a signaling implementation, and receive from it, respectively. Hope that can be a helpful starting point.
