### ISSUE TITLE
working with kurento

### ISSUE THREAD

**Issue by wsteelenyc** [bengreenier/webrtc-unity-plugin#11]
I'm trying to figure out what would be required to get this to work with Kurento Media Server.  I understand the signaling part, but would much need to change in regards to sending the webrtc video to the kurento server?

**Comment by bengreenier** [comment]
Sorry, i'm not sure what Kurento Server is, or how it works. Perhaps that's a better question for it's creators? From the perspective of this library - anything that "speaks" WebRTC and is compatible with the m71 version (`m71` being the chromium milestone name that this version of the WebRTC source comes from), it should work just great.
