### ISSUE TITLE
node.js socket connection using https instead of GET/POST

### ISSUE THREAD

**Issue by freeseus** [bengreenier/webrtc-unity-plugin#12]
Hey Ben... apologies, this isn't a bug, but had a question regarding using this Unity plugin to work with node.js sockets (using https)...

The webrtc-unity-plugin is doing almost exactly what I need but we're not using GET/POST from the node.js server.

Apologies for reaching out here. Is it possible for you to point me in the right direction?
You can find me on Discord: Freeseus#7761

Appreciate it.

**Comment by bengreenier** [comment]
you can replace the logic in [WebrtcSignalControls](https://github.com/bengreenier/webrtc-unity-plugin/blob/master/Assets/UnityWebrtc/WebrtcSignalControls.cs) to implement a similar flow, but communicating with signaling differently - ctrl+f `PeerEventsInstance` in that file - hope that helps!
