### ISSUE TITLE
Unity to Web Clinet

### ISSUE THREAD

**Issue by devipt97** [bengreenier/webrtc-unity-plugin#13]
It's NOT AN ISSUE. I am just asking a question. Sorry for reaching out here.
Does the current implementation allows interact with other WebRTC client other that Unity base. Meaning given that we have right implementation of signaling server on both end i.e unity project and web based client, is it possible to fetch video data from web based client and render it in unity and vice versa.

**Comment by bengreenier** [comment]
yes that should be possible
