### ISSUE TITLE
How to send data

### ISSUE THREAD

**Issue by nav-cng** [bengreenier/webrtc-unity-plugin#14]
I'm new to webRTC, could you please let me know how to send simple string data.
I'm able to send video to another peer but couldn't figure out how to data

**Comment by bengreenier** [comment]
Hello,

You should be able to use [`WebrtcPeerEvents.AddDataChannel()`](https://github.com/bengreenier/webrtc-unity-plugin/blob/master/Assets/UnityWebrtc/WebrtcPeerEvents.cs#L272) and [`WebrtcPeerEvents.SendDataViaDataChannel`](https://github.com/bengreenier/webrtc-unity-plugin/blob/master/Assets/UnityWebrtc/WebrtcPeerEvents.cs#L335) to send string data over a data channel.
