### ISSUE TITLE
Video stream from HoloLens is not a Mixed Reality Capture

### ISSUE THREAD

**Issue by michael-house** [bengreenier/webrtc-unity-plugin#8]
The video coming from the HoloLens is just straight video from the device camera. When using m71 from webrtc-uwp, the video coming from the HoloLens is a mixed reality capture. Meaning that the video stream is a composite of the device camera, plus the scene objects (holograms).

**Comment by michael-house** [comment]
Appears to be tracked here upstream:

https://github.com/webrtc-uwp/webrtc-uwp-sdk/issues/130

**Comment by bengreenier** [comment]
I'm going to close this one with the guidance that folks interested in this scenario take a look at https://github.com/microsoft/MixedReality-WebRTC
