### ISSUE TITLE
Data Channel Fails

### ISSUE THREAD

**Issue by markgrossnickle** [bengreenier/webrtc-unity-plugin#9]
The Data Channel fails to create due to configuration issues.

In DataChannel Init it checks the following:
>   if (data_channel_type_ == cricket::DCT_RTP) {
    if (config.reliable || config.id != -1 || config.maxRetransmits != -1 ||
        config.maxRetransmitTime != -1) {
      RTC_LOG(LS_ERROR) << "Failed to initialize the RTP data channel due to "
                           "invalid DataChannelInit.";

In simple_peer_connection.cc's CreatePeerConnection method it sets config_.enable_rtp_data_channel = true;

In simple_peer_connection.cc's CreateDataChannel method it sets
init.reliable = true;

We either need to switch to SCTP for a reliable connection or make the connection unreliable.

**Comment by Holo-Krzysztof** [comment]
As far as I know RTP data channels are deprecated, so switching to SCTP is the way to go.

**Comment by bengreenier** [comment]
yes this makes sense. I won't have a change to implement this anytime soon though, unfortunately as i've had to switch focus at work. Looks like the [google version](https://webrtc.googlesource.com/src/+/refs/heads/master/examples/unityplugin/simple_peer_connection.cc#193) is still using rtp as well.

**Comment by iamrohit1** [comment]
@markgrossnickle thanks for fix! I was able to get data channel set up after I marked the connection unreliable.. however I do not get the local data channel ready callback from webrtc.. nor can I send messages via data channel .. any idea what could be the issue?

**Comment by markgrossnickle** [comment]
Its been awhile. I think Microsoft released a webrtc unity build now though. I'd check the latest here as its probably much more up to date than this and hopefully has data channels working:
https://github.com/microsoft/MixedReality-WebRTC
